name: Test ClusterShell setup action

on:
    push:
        branches: "*"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Test ClusterShell setup action
              uses: ./
            - name: Verify ClusterShell installation
              shell: bash
              run: nodeset -L
